# Generated by Django 5.0.1 on 2024-02-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_content_post_full_text_post_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='cover_img/default.jpg', upload_to='cover_img'),
            preserve_default=False,
        ),
    ]
